Repository gausstalk/gausstalk-backend, pull requests merged in 2022-06, with the labels that each got.

#18 specify async functions
  apps/user/endpoints/v1/auth.py
  main.py
Labels: enhancement

#20 github actions deploy to aks
  .github/workflows/main-to-aks.yml
  manifests/deployment.yaml
  manifests/ingress.yaml
Labels: feature

#21 implement creating a user
  apps/user/endpoints/v1/__init__.py
  apps/user/endpoints/v1/auth.py
  apps/user/endpoints/v1/user.py
  apps/user/models/auth.py
  apps/user/services/__init__.py
  apps/user/services/auth_service.py
  main.py
  requirements.in
  requirements.txt
  services/mongo_service.py
Labels: feature

#22 add mongo db environment variables
  manifests/deployment.yaml
Labels: bug

#23 fix raise exception in auth_user
  apps/user/endpoints/v1/user.py
  apps/user/services/auth_service.py
Labels: bug

#25 amend get_user function response
  apps/user/endpoints/v1/user.py
Labels: enhancement

#28 contain sender name in websocket
  apps/chat/endpoints/v1/websocket.py
  apps/user/services/auth_service.py
Labels: bug

#29 edit exception handling of decode in websocket_endpoint
  apps/chat/endpoints/v1/websocket.py
Labels: bug

#30 add sender_mail into chat message format
  apps/chat/endpoints/v1/websocket.py
  apps/chat/models/chat.py
Labels: bug

#31 delete devspace files
  devspace.yaml
  devspace_start.sh
Labels: enhancement

#35 fix timezone to Asia/Seoul for k8s
  Dockerfile
Labels: bug

#44 prevent sending multiple emails
  services/__init__.py
  services/email.py
Labels: bug

#43 set refresh token expire date
  apps/user/endpoints/v1/auth.py
  apps/user/endpoints/v1/user.py
Labels: enhancement
